# Generated by Django 4.2.7 on 2023-11-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanCalculatorAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='months',
            field=models.IntegerField(default=12),
        ),
    ]
