# Generated by Django 4.2.7 on 2023-11-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanCalculatorAPI', '0002_loan_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='lending_rate',
            field=models.FloatField(),
        ),
    ]
