# Generated by Django 4.2.7 on 2023-11-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanCalculatorAPI', '0004_alter_loan_lending_rate_alter_loan_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='months',
            field=models.FloatField(default=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
