# Generated by Django 4.2.7 on 2023-11-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanCalculatorAPI', '0005_alter_loan_months_alter_loan_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='id',
        ),
        migrations.AlterField(
            model_name='loan',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
